import { Inbox } from '@/components/Inbox'
import type { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
	return (
		<div className='overflow-x-hidden'>
			{children}
		</div>
	)
}
