import type { Metadata } from 'next'

import TanstackProvider from '@/providers/TanstackProvider'
import { Header } from '@/components'
import './globals.scss'


export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className='overflow-x-hidden'>
				<TanstackProvider>
					<Header />
					{children}
				</TanstackProvider>
			</body>
		</html>
	)
}
